# --------------------------------
# standard jekyll configs
# --------------------------------

permalink: /:year/:month/:title
paginate: 10

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# --------------------------------
# my own config variables
# --------------------------------

# URL to atom feed (registered at feedburner.com)
feedburner_url: http://feeds.feedburner.com/spier

# name of the author
author: Sebastian Spier

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# I can also try github favoured markdown
# kramdown:
  # input: GFM

url_root: http://spier.hu

