# --------------------------------
# standard jekyll configs
# --------------------------------

markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:title
rdiscount:
  extensions: [smart]
paginate: 10

# --------------------------------
# my own config variables
# --------------------------------

# URL to atom feed (registered at feedburner.com)
feedburner_url: http://feeds.feedburner.com/spier

# name of the author
author: Sebastian Spier

gems:
  - jekyll-sitemap
  - jemoji

# I can also try github favoured markdown
# kramdown:
  # input: GFM

url_root: http://spier.hu
