markdown: rdiscount
pygments: true
permalink: /:year/:month/:title
auto: true
rdiscount:
  extensions: [smart]
paginate: 10


# -----------------
# my own config variables. 
# -----------------
    
# the trailing slash is needed
# base_url: http://spier.github.com/
base_url: http://spier.hu/

# URL to atom feed (registered at feedburner.com)
feedburner_url: http://feeds.feedburner.com/spier

# name of the author
author: Sebastian Spier
