# --------------------------------
# standard jekyll configs
# --------------------------------

markdown: rdiscount
pygments: true
permalink: /:year/:month/:title
rdiscount:
  extensions: [smart]
paginate: 10

baseurl: http://spier.hu

# --------------------------------
# my own config variables
# --------------------------------

# URL to atom feed (registered at feedburner.com)
feedburner_url: http://feeds.feedburner.com/spier

# name of the author
author: Sebastian Spier

gems:
  - jekyll-sitemap
